ezpublish:
  system:
    default:
      fieldtypes:
        ezrichtext:
          custom_tags: [ezyoutube]

ezrichtext:
  custom_tags:
    ezyoutube:
      template: EzSystemsExtendingTutorialBundle:field_type/ezrichtext/custom_tag:ezyoutube.html.twig
      icon: '/bundles/ezplatformadminui/img/ez-icons.svg#video'
      attributes:
        title:
          type: string
          required: true
          default_value: ''
        video_url:
          type: string
          required: true
        width:
          type: number
          required: true
          default_value: 640
        height:
          type: number
          required: true
          default_value: 360
        autoplay:
          type: boolean
          default_value: false
        align:
          type: choice
          required: false
          default_value: left
          choices: [left, center, right]